<?php

/**
 * @file
 * AWS SQS module functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aws_sqs_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    // Main module help for the paragraphs module.
    case 'help.page.aws_sqs':
      $output = t('Amazon Simple Queue System define easy interface for AWS SQS.');

      break;
  }
  return $output;
}
